/**
 * PULSE ROUTER — COIMBATORE (SAI BABA COLONY) CONTROL ROOM & DISPATCH PLATFORM
 * Master Data: Coimbatore Trauma Network, Fleet Roster, Active Cases & Presets
 */

// 1. Configurable Medical Incident Categories
export const MEDICAL_INCIDENT_CATEGORIES = {
  ROAD_ACCIDENT: {
    id: 'ROAD_ACCIDENT',
    label: 'Road Accident',
    code: 'TRAUMA-RTA',
    priority: 'CRITICAL',
    sublabel: 'High-Speed Collision / Severe Trauma',
    icon: 'car',
    color: '#e11d48',
    requiredDept: 'TRAUMA',
    equipmentRequired: ['Spine Board', 'Oxygen Kit', 'Suction Unit', 'Collars']
  },
  CARDIAC_EMERGENCY: {
    id: 'CARDIAC_EMERGENCY',
    label: 'Cardiac Emergency',
    code: 'CARD-MI',
    priority: 'CRITICAL',
    sublabel: 'Acute Chest Pain / Myocardial Infarction',
    icon: 'heart-pulse',
    color: '#e11d48',
    requiredDept: 'CARDIAC',
    equipmentRequired: ['12-Lead ECG Monitor', 'Defibrillator', 'Aspirin/Nitro', 'CPR Board']
  },
  TRAUMA: {
    id: 'TRAUMA',
    label: 'Major Trauma',
    code: 'TRAUMA-GEN',
    priority: 'CRITICAL',
    sublabel: 'Blunt/Penetrating Severe Injury',
    icon: 'activity',
    color: '#f97316',
    requiredDept: 'TRAUMA',
    equipmentRequired: ['Tourniquets', 'Hemostatic Gauze', 'Splints', 'Pressure Infusers']
  },
  STROKE_NEURO: {
    id: 'STROKE_NEURO',
    label: 'Acute Stroke',
    code: 'NEURO-CVA',
    priority: 'CRITICAL',
    sublabel: 'Facial Droop / Hemiplegia / Aphasia',
    icon: 'brain',
    color: '#a855f7',
    requiredDept: 'NEURO',
    equipmentRequired: ['Glucometer', 'NIHSS Protocol Kit', 'Oxygen Mask', 'IV Cannulas']
  },
  BREATHING: {
    id: 'BREATHING',
    label: 'Severe Respiratory',
    code: 'RESP-ACUTE',
    priority: 'HIGH',
    sublabel: 'Acute Dyspnea / Asthma / Hypoxia',
    icon: 'wind',
    color: '#3b82f6',
    requiredDept: 'PULMONOLOGY',
    equipmentRequired: ['Nebulizer', 'Bag-Valve-Mask', 'Pulse Oximeter', 'Salbutamol']
  },
  BURNS: {
    id: 'BURNS',
    label: 'Severe Burns',
    code: 'BURN-MAJOR',
    priority: 'CRITICAL',
    sublabel: 'Thermal / Chemical / Electrical Burns',
    icon: 'flame',
    color: '#ef4444',
    requiredDept: 'BURNS',
    equipmentRequired: ['Sterile Burn Sheets', 'Normal Saline', 'Analgesics', 'Cool Dressings']
  },
  PEDIATRIC: {
    id: 'PEDIATRIC',
    label: 'Pediatric Emergency',
    code: 'PED-CRIT',
    priority: 'CRITICAL',
    sublabel: 'Infant / Child Critical Illness',
    icon: 'baby',
    color: '#06b6d4',
    requiredDept: 'PEDIATRIC',
    equipmentRequired: ['Pediatric BVM', 'Broselow Tape', 'Pediatric Defib Pads']
  },
  OBSTETRIC: {
    id: 'OBSTETRIC',
    label: 'Obstetric Emergency',
    code: 'OB-LABOR',
    priority: 'HIGH',
    sublabel: 'Active Labor / Complicated Pregnancy',
    icon: 'heart-handshake',
    color: '#ec4899',
    requiredDept: 'OBGYN',
    equipmentRequired: ['Emergency Delivery Kit', 'Neonatal Suction', 'Cord Clamps']
  },
  UNCONSCIOUS: {
    id: 'UNCONSCIOUS',
    label: 'Unconscious / Syncope',
    code: 'GEN-LOC',
    priority: 'CRITICAL',
    sublabel: 'Unresponsive / Unknown Origin',
    icon: 'user-x',
    color: '#dc2626',
    requiredDept: 'EMERGENCY',
    equipmentRequired: ['Airway Adjuncts', 'Glucometer', 'IV Start Kits', 'Monitor']
  },
  OTHER: {
    id: 'OTHER',
    label: 'General Medical',
    code: 'GEN-MED',
    priority: 'NORMAL',
    sublabel: 'Acute Abdomen / Sepsis / Intoxication',
    icon: 'help-circle',
    color: '#6b7280',
    requiredDept: 'GENERAL',
    equipmentRequired: ['First Aid Kit', 'Vitals Monitor', 'Stretcher']
  }
};

// 2. Coimbatore Tertiary Emergency Trauma Centers Database
export const COIMBATORE_HOSPITALS = [
  {
    id: 'hosp-ganga',
    name: 'Ganga Hospital & Trauma Centre',
    shortName: 'Ganga Hospital',
    address: '313 Mettupalayam Rd, Sai Baba Colony, Coimbatore 641043',
    zone: 'Sai Baba Colony / North CBE',
    lat: 11.0280,
    lng: 76.9490,
    phone: '+91 422 248 5000',
    erStatus: 'OPEN',
    icuBeds: 6,
    totalIcuBeds: 24,
    wardBeds: 40,
    otAvailable: true,
    ctScanReady: true,
    cathLabActive: true,
    capabilities: ['TRAUMA', 'BURNS', 'NEURO', 'RESPIRATORY'],
    specialties: ['Level 1 Polytrauma & Orthopaedics', 'Plastic & Burn Surgery', 'Spine & Neuro ICU'],
    tags: ['Next to Sai Baba Colony', 'Polytrauma Bay Ready', 'ICU Available (6 beds)']
  },
  {
    id: 'hosp-gknm',
    name: 'G. Kuppuswamy Naidu Memorial Hospital (GKNM)',
    shortName: 'GKNM Hospital',
    address: 'P.N. Palayam, Avinashi Road, Coimbatore 641037',
    zone: 'Central Coimbatore',
    lat: 11.0155,
    lng: 76.9745,
    phone: '+91 422 432 4444',
    erStatus: 'OPEN',
    icuBeds: 5,
    totalIcuBeds: 20,
    wardBeds: 35,
    otAvailable: true,
    ctScanReady: true,
    cathLabActive: true,
    capabilities: ['CARDIAC', 'PEDIATRIC', 'RESPIRATORY', 'TRAUMA'],
    specialties: ['Advanced Cardiology & Cath Lab', 'Cardiothoracic ICU', 'Pediatric Critical Care'],
    tags: ['Cath Lab Active 24/7', 'ICU Available (5 beds)', 'Cardiac Resuscitation Team']
  },
  {
    id: 'hosp-ramakrishna',
    name: 'Sri Ramakrishna Hospital',
    shortName: 'Ramakrishna Hosp',
    address: '395 Sarojini Naidu Rd, Sidhapudur, Coimbatore 641044',
    zone: 'Central Coimbatore',
    lat: 11.0210,
    lng: 76.9780,
    phone: '+91 422 450 0000',
    erStatus: 'OPEN',
    icuBeds: 4,
    totalIcuBeds: 18,
    wardBeds: 30,
    otAvailable: true,
    ctScanReady: true,
    cathLabActive: true,
    capabilities: ['NEURO', 'CARDIAC', 'TRAUMA', 'RESPIRATORY'],
    specialties: ['Comprehensive Stroke Center', 'Neuro Trauma Bay', 'Multi-Specialty ICU'],
    tags: ['Stroke Care Unit Active', 'ICU Available (4 beds)', 'Trauma OR Ready']
  },
  {
    id: 'hosp-psg',
    name: 'PSG Hospitals (PSG IMS&R)',
    shortName: 'PSG Hospitals',
    address: 'Avinashi Road, Peelamedu, Coimbatore 641004',
    zone: 'East Coimbatore',
    lat: 11.0360,
    lng: 77.0310,
    phone: '+91 422 434 5353',
    erStatus: 'OPEN',
    icuBeds: 8,
    totalIcuBeds: 30,
    wardBeds: 50,
    otAvailable: true,
    ctScanReady: true,
    cathLabActive: true,
    capabilities: ['TRAUMA', 'CARDIAC', 'PEDIATRIC', 'BURNS', 'NEURO'],
    specialties: ['Tertiary Emergency & Trauma Bay', 'Neonatal & Pediatric ICU', 'Multi-Organ Transplant'],
    tags: ['Level 1 Emergency Wing', 'ICU Available (8 beds)', '24/7 MRI & CT']
  },
  {
    id: 'hosp-kmch',
    name: 'KMCH (Kovai Medical Center & Hospital)',
    shortName: 'KMCH Hospital',
    address: '99 Avinashi Road, Civil Aerodrome Post, Coimbatore 641014',
    zone: 'Airport / East CBE',
    lat: 11.0550,
    lng: 77.0420,
    phone: '+91 422 432 3800',
    erStatus: 'OPEN',
    icuBeds: 7,
    totalIcuBeds: 28,
    wardBeds: 45,
    otAvailable: true,
    ctScanReady: true,
    cathLabActive: true,
    capabilities: ['TRAUMA', 'CARDIAC', 'NEURO', 'RESPIRATORY', 'BURNS'],
    specialties: ['Polytrauma Bay & Helipad', 'Interventional Cath Lab', 'Neuro Intensive Care'],
    tags: ['Comprehensive Trauma Centre', 'ICU Available (7 beds)', 'ECMO Unit Ready']
  },
  {
    id: 'hosp-cmch',
    name: 'Coimbatore Medical College Hospital (Govt GH)',
    shortName: 'Govt Hospital CBE',
    address: 'Trichy Road, Gopalapuram, Coimbatore 641018',
    zone: 'South Coimbatore',
    lat: 10.9985,
    lng: 76.9660,
    phone: '+91 422 230 1393',
    erStatus: 'OPEN',
    icuBeds: 3,
    totalIcuBeds: 25,
    wardBeds: 60,
    otAvailable: true,
    ctScanReady: true,
    cathLabActive: false,
    capabilities: ['TRAUMA', 'BURNS', 'EMERGENCY', 'OBGYN'],
    specialties: ['Government Tertiary Casualty', 'Major Burns Ward', 'Emergency ORs'],
    tags: ['Govt Emergency Bay', 'ICU Available (3 beds)', '24/7 Blood Bank']
  },
  {
    id: 'hosp-kg',
    name: 'KG Hospital & Post Graduate Medical Institute',
    shortName: 'KG Hospital',
    address: 'Govt Arts College Rd, Gopalapuram, Coimbatore 641018',
    zone: 'South Central CBE',
    lat: 11.0005,
    lng: 76.9680,
    phone: '+91 422 221 2121',
    erStatus: 'OPEN',
    icuBeds: 4,
    totalIcuBeds: 16,
    wardBeds: 28,
    otAvailable: true,
    ctScanReady: true,
    cathLabActive: true,
    capabilities: ['CARDIAC', 'NEURO', 'TRAUMA', 'RESPIRATORY'],
    specialties: ['Cardiac Cath Lab', 'Neurovascular Intervention', 'Critical Care'],
    tags: ['Cardiac Unit Active', 'ICU Available (4 beds)']
  },
  {
    id: 'hosp-gem',
    name: 'GEM Hospital & Research Centre',
    shortName: 'GEM Hospital',
    address: '45 Pankaja Mills Rd, Ramanathapuram, Coimbatore 641045',
    zone: 'South-East CBE',
    lat: 11.0020,
    lng: 76.9940,
    phone: '+91 422 232 5100',
    erStatus: 'OPEN',
    icuBeds: 3,
    totalIcuBeds: 12,
    wardBeds: 20,
    otAvailable: true,
    ctScanReady: true,
    cathLabActive: false,
    capabilities: ['TRAUMA', 'EMERGENCY', 'RESPIRATORY'],
    specialties: ['Gastrointestinal & Laparoscopic Emergencies', 'Surgical ICU'],
    tags: ['Surgical Emergency Ready', 'ICU Available (3 beds)']
  },
  {
    id: 'hosp-royalcare',
    name: 'Royal Care Super Speciality Hospital',
    shortName: 'Royal Care Hosp',
    address: '1/520 L&T Bypass Road, Neelambur, Coimbatore 641062',
    zone: 'East Corridor CBE',
    lat: 11.0680,
    lng: 77.0850,
    phone: '+91 422 222 7000',
    erStatus: 'OPEN',
    icuBeds: 5,
    totalIcuBeds: 20,
    wardBeds: 35,
    otAvailable: true,
    ctScanReady: true,
    cathLabActive: true,
    capabilities: ['NEURO', 'CARDIAC', 'TRAUMA', 'RESPIRATORY'],
    specialties: ['Comprehensive Neuro & Stroke Bay', 'Interventional Cardiology', 'Polytrauma'],
    tags: ['Highway Trauma Bay', 'ICU Available (5 beds)']
  }
];

export const CHENNAI_HOSPITALS = COIMBATORE_HOSPITALS;

// 3. Ambulance Fleet Roster (Centered around Sai Baba Colony & Greater Coimbatore)
export const AMBULANCE_FLEET = [
  {
    id: 'AMB-1042',
    registration: 'TN 38 AB 4521',
    type: 'ALS (Advanced Life Support)',
    typeCode: 'ALS',
    driverName: 'Arun Kumar',
    driverPhone: '+91 98401 22345',
    driverId: 'DRV-1042',
    status: 'AVAILABLE',
    dutyStatus: 'ON_DUTY',
    lat: 11.0275,
    lng: 76.9430,
    baseStation: 'Sai Baba Colony 11th Cross Hub',
    speed: 0,
    heading: 45,
    gpsStatus: 'ACTIVE',
    signalStrength: 'EXCELLENT',
    network: '5G NSA',
    fuelLevel: 88,
    oxygenLevel: 94,
    equipment: ['12-Lead ECG Monitor', 'Ventilator', 'Biphasic Defibrillator', 'Suction Unit'],
    activeCaseId: null,
    lastUpdate: '2s ago',
    stats: { completedToday: 4, avgResponseMin: 3.8, onTimeRate: '98%' }
  },
  {
    id: 'AMB-1018',
    registration: 'TN 38 CD 1018',
    type: 'Trauma ALS',
    typeCode: 'ALS',
    driverName: 'Karthik Raja',
    driverPhone: '+91 98402 33456',
    driverId: 'DRV-7701',
    status: 'AVAILABLE',
    dutyStatus: 'ON_DUTY',
    lat: 11.0310,
    lng: 76.9480,
    baseStation: 'Mettupalayam Rd Sai Baba Colony',
    speed: 0,
    heading: 90,
    gpsStatus: 'ACTIVE',
    signalStrength: 'EXCELLENT',
    network: '5G NSA',
    fuelLevel: 76,
    oxygenLevel: 91,
    equipment: ['Spine Board', 'Defibrillator', 'Suction Kit', 'Oxygen Tank'],
    activeCaseId: null,
    lastUpdate: '4s ago',
    stats: { completedToday: 3, avgResponseMin: 4.1, onTimeRate: '96%' }
  },
  {
    id: 'AMB-1031',
    registration: 'TN 38 EF 2234',
    type: 'Cardiac ALS',
    typeCode: 'ALS',
    driverName: 'Priya Kumar',
    driverPhone: '+91 98403 44567',
    driverId: 'DRV-7702',
    status: 'AVAILABLE',
    dutyStatus: 'ON_DUTY',
    lat: 11.0120,
    lng: 76.9510,
    baseStation: 'DB Road, RS Puram Base',
    speed: 0,
    heading: 180,
    gpsStatus: 'ACTIVE',
    signalStrength: 'GOOD',
    network: '4G LTE',
    fuelLevel: 92,
    oxygenLevel: 98,
    equipment: ['12-Lead ECG Monitor', 'Defibrillator', 'Transcutaneous Pacing'],
    activeCaseId: null,
    lastUpdate: '3s ago',
    stats: { completedToday: 5, avgResponseMin: 4.5, onTimeRate: '100%' }
  },
  {
    id: 'AMB-1055',
    registration: 'TN 38 GH 8899',
    type: 'ALS (Advanced Life Support)',
    typeCode: 'ALS',
    driverName: 'Vignesh S.',
    driverPhone: '+91 98404 55678',
    driverId: 'DRV-7703',
    status: 'AVAILABLE',
    dutyStatus: 'ON_DUTY',
    lat: 11.0180,
    lng: 76.9680,
    baseStation: 'Gandhipuram Cross Cut Station',
    speed: 0,
    heading: 270,
    gpsStatus: 'ACTIVE',
    signalStrength: 'EXCELLENT',
    network: '5G NSA',
    fuelLevel: 82,
    oxygenLevel: 89,
    equipment: ['12-Lead ECG', 'Ventilator', 'Defibrillator'],
    activeCaseId: null,
    lastUpdate: '6s ago',
    stats: { completedToday: 4, avgResponseMin: 4.9, onTimeRate: '95%' }
  },
  {
    id: 'AMB-1064',
    registration: 'TN 38 IJ 7766',
    type: 'Neonatal & Pediatric ALS',
    typeCode: 'NICU',
    driverName: 'Meena Kumari',
    driverPhone: '+91 98405 66789',
    driverId: 'DRV-7704',
    status: 'AVAILABLE',
    dutyStatus: 'ON_DUTY',
    lat: 11.0320,
    lng: 77.0150,
    baseStation: 'Peelamedu Avinashi Road',
    speed: 0,
    heading: 0,
    gpsStatus: 'ACTIVE',
    signalStrength: 'EXCELLENT',
    network: '5G NSA',
    fuelLevel: 95,
    oxygenLevel: 97,
    equipment: ['Transport Incubator', 'Neonatal Ventilator', 'Infusion Pumps'],
    activeCaseId: null,
    lastUpdate: '1s ago',
    stats: { completedToday: 2, avgResponseMin: 3.9, onTimeRate: '100%' }
  },
  {
    id: 'AMB-1077',
    registration: 'TN 38 KL 9911',
    type: 'BLS (Basic Life Support)',
    typeCode: 'BLS',
    driverName: 'Suresh M.',
    driverPhone: '+91 98406 77890',
    driverId: 'DRV-7705',
    status: 'AVAILABLE',
    dutyStatus: 'ON_DUTY',
    lat: 11.0380,
    lng: 76.9750,
    baseStation: 'Ganapathy Bus Stand Hub',
    speed: 0,
    heading: 135,
    gpsStatus: 'ACTIVE',
    signalStrength: 'GOOD',
    network: '4G LTE',
    fuelLevel: 70,
    oxygenLevel: 85,
    equipment: ['AED', 'Oxygen Cylinder', 'Splint Set'],
    activeCaseId: null,
    lastUpdate: '5s ago',
    stats: { completedToday: 3, avgResponseMin: 5.2, onTimeRate: '94%' }
  },
  {
    id: 'AMB-1089',
    registration: 'TN 38 MN 3344',
    type: 'ALS (Advanced Life Support)',
    typeCode: 'ALS',
    driverName: 'Anand Raj',
    driverPhone: '+91 98407 88901',
    driverId: 'DRV-7706',
    status: 'AVAILABLE',
    dutyStatus: 'ON_DUTY',
    lat: 11.0190,
    lng: 76.9050,
    baseStation: 'Vadavalli Main Road Station',
    speed: 0,
    heading: 220,
    gpsStatus: 'ACTIVE',
    signalStrength: 'GOOD',
    network: '4G LTE',
    fuelLevel: 84,
    oxygenLevel: 92,
    equipment: ['12-Lead ECG', 'Ventilator', 'Defibrillator'],
    activeCaseId: null,
    lastUpdate: '7s ago',
    stats: { completedToday: 4, avgResponseMin: 4.8, onTimeRate: '97%' }
  },
  {
    id: 'AMB-1092',
    registration: 'TN 38 OP 5566',
    type: 'BLS (Basic Life Support)',
    typeCode: 'BLS',
    driverName: 'Deepa Lakshmi',
    driverPhone: '+91 98408 99012',
    driverId: 'DRV-7707',
    status: 'AVAILABLE',
    dutyStatus: 'ON_DUTY',
    lat: 11.0750,
    lng: 76.9380,
    baseStation: 'Thudiyalur Junction Hub',
    speed: 0,
    heading: 90,
    gpsStatus: 'ACTIVE',
    signalStrength: 'EXCELLENT',
    network: '5G NSA',
    fuelLevel: 80,
    oxygenLevel: 90,
    equipment: ['AED', 'Oxygen Kit', 'First Aid Kit'],
    activeCaseId: null,
    lastUpdate: '10s ago',
    stats: { completedToday: 2, avgResponseMin: 5.4, onTimeRate: '92%' }
  },
  {
    id: 'AMB-1105',
    registration: 'TN 38 QR 7788',
    type: 'Polytrauma ALS',
    typeCode: 'ALS',
    driverName: 'Manoj Kumar',
    driverPhone: '+91 98409 00123',
    driverId: 'DRV-7708',
    status: 'AVAILABLE',
    dutyStatus: 'ON_DUTY',
    lat: 11.0820,
    lng: 76.9980,
    baseStation: 'Saravanampatti IT Hub',
    speed: 0,
    heading: 315,
    gpsStatus: 'ACTIVE',
    signalStrength: 'EXCELLENT',
    network: '5G NSA',
    fuelLevel: 89,
    oxygenLevel: 96,
    equipment: ['12-Lead ECG', 'Defibrillator', 'Vacuum Mattress'],
    activeCaseId: null,
    lastUpdate: '3s ago',
    stats: { completedToday: 3, avgResponseMin: 4.6, onTimeRate: '98%' }
  },
  {
    id: 'AMB-1114',
    registration: 'TN 38 ST 9900',
    type: 'Cardiac ALS',
    typeCode: 'ALS',
    driverName: 'Ravi Shankar',
    driverPhone: '+91 98410 11234',
    driverId: 'DRV-7709',
    status: 'AVAILABLE',
    dutyStatus: 'ON_DUTY',
    lat: 10.9880,
    lng: 76.9620,
    baseStation: 'Ukkadam Bus Terminal',
    speed: 0,
    heading: 0,
    gpsStatus: 'ACTIVE',
    signalStrength: 'GOOD',
    network: '4G LTE',
    fuelLevel: 75,
    oxygenLevel: 88,
    equipment: ['12-Lead ECG', 'External Pacing', 'Ventilator'],
    activeCaseId: null,
    lastUpdate: '8s ago',
    stats: { completedToday: 4, avgResponseMin: 5.0, onTimeRate: '95%' }
  },
  {
    id: 'AMB-1120',
    registration: 'TN 38 UV 1122',
    type: 'BLS (Basic Life Support)',
    typeCode: 'BLS',
    driverName: 'Divya Mohan',
    driverPhone: '+91 98411 22345',
    driverId: 'DRV-7710',
    status: 'AVAILABLE',
    dutyStatus: 'ON_DUTY',
    lat: 10.9990,
    lng: 77.0250,
    baseStation: 'Singanallur Station',
    speed: 0,
    heading: 180,
    gpsStatus: 'ACTIVE',
    signalStrength: 'EXCELLENT',
    network: '4G LTE',
    fuelLevel: 91,
    oxygenLevel: 95,
    equipment: ['AED', 'Oxygen System', 'Stretcher'],
    activeCaseId: null,
    lastUpdate: '5s ago',
    stats: { completedToday: 2, avgResponseMin: 5.6, onTimeRate: '93%' }
  },
  {
    id: 'AMB-1191',
    registration: 'TN 38 WX 3344',
    type: 'ALS (Advanced Life Support)',
    typeCode: 'ALS',
    driverName: 'Lakshmi N.',
    driverPhone: '+91 98412 33456',
    driverId: 'DRV-7711',
    status: 'AVAILABLE',
    dutyStatus: 'ON_DUTY',
    lat: 11.0290,
    lng: 76.9410,
    baseStation: 'Sai Baba Colony NSR Road North',
    speed: 0,
    heading: 90,
    gpsStatus: 'ACTIVE',
    signalStrength: 'EXCELLENT',
    network: '5G NSA',
    fuelLevel: 94,
    oxygenLevel: 98,
    equipment: ['12-Lead ECG', 'Ventilator', 'Defibrillator'],
    activeCaseId: null,
    lastUpdate: '2s ago',
    stats: { completedToday: 5, avgResponseMin: 3.5, onTimeRate: '100%' }
  }
];

// 4. Initial Active Emergencies (Centered around Sai Baba Colony)
export const INITIAL_ACTIVE_CASES = [
  {
    caseId: 'ER-2026-69655',
    priority: 'CRITICAL',
    incidentType: 'ROAD_ACCIDENT',
    title: 'Two-Wheeler Collision at NSR Road',
    caller: {
      name: 'Senthil Nathan',
      phone: '+91 94440 11223',
      callTime: '16:10:12',
      duration: '01:14'
    },
    patientDetails: {
      name: 'Ramesh Kumar (34M)',
      age: '34 yrs',
      gender: 'Male',
      count: 1,
      condition: 'Two-wheeler skid, active limb bleed and concussion',
      avpu: 'Pain (P)',
      breathing: 'Labored',
      severeBleeding: 'Yes'
    },
    location: {
      address: 'NSR Road, Sai Baba Colony, Coimbatore',
      landmark: 'Near Avila Convent & Ganga Hospital',
      latitude: 11.0275,
      longitude: 76.9430,
      accessNotes: 'Peak evening traffic on NSR Road'
    },
    assignedAmbulanceId: 'AMB-1042',
    assignedDriver: {
      id: 'DRV-1042',
      name: 'Arun Kumar',
      phone: '+91 98401 22345',
      reg: 'TN 38 AB 4521'
    },
    etaMinutes: 3,
    distanceKm: 1.2,
    assignedHospitalId: 'hosp-ganga',
    primaryHospitalId: 'hosp-ganga',
    hospitalChanged: false,
    state: 'NAVIGATING_TO_INCIDENT',
    timeline: [
      { step: 'CALL_RECEIVED', label: 'Call Received from +91 94440 11223', time: '16:10:12', desc: 'Inbound Emergency Hotline' },
      { step: 'CASE_CREATED', label: 'Triage Confirmed (Code Red)', time: '16:10:45', desc: 'Sai Baba Colony NSR Road' },
      { step: 'AMBULANCE_ASSIGNED', label: 'AMB-1042 Allotted to Case', time: '16:10:50', desc: 'Closest unit 1.2km away' },
      { step: 'ACCEPTED', label: 'Driver Arun Kumar Accepted in 3s', time: '16:10:53', desc: 'En Route with Siren Active' }
    ],
    createdAt: '16:10:12'
  }
];

export const INITIAL_ACTIVE_EMERGENCIES = INITIAL_ACTIVE_CASES;

// 5. Emergency History Records
export const INITIAL_HISTORY_CASES = [
  {
    caseId: 'ER-2026-69640',
    date: '2026-08-30',
    time: '14:20:15',
    priority: 'CRITICAL',
    incidentType: 'ROAD_ACCIDENT',
    title: 'Mettupalayam Road Vehicle Collision',
    location: 'Mettupalayam Road, Sai Baba Colony, Coimbatore',
    ambulance: 'AMB-1018',
    driver: 'Karthik Raja',
    hospital: 'Ganga Hospital & Trauma Centre',
    primaryHospital: 'Ganga Hospital',
    hospitalChanged: false,
    rerouteReason: null,
    totalDistance: '2.4 km',
    totalResponseTime: '12 min',
    status: 'COMPLETED'
  },
  {
    caseId: 'ER-2026-69632',
    date: '2026-08-30',
    time: '12:45:00',
    priority: 'CRITICAL',
    incidentType: 'CARDIAC_EMERGENCY',
    title: 'Acute STEMI / Cardiac Arrest',
    location: 'DB Road, RS Puram, Coimbatore',
    ambulance: 'AMB-1031',
    driver: 'Priya Kumar',
    hospital: 'GKNM Hospital, Avinashi Rd',
    primaryHospital: 'GKNM Hospital',
    hospitalChanged: false,
    rerouteReason: null,
    totalDistance: '4.1 km',
    totalResponseTime: '15 min',
    status: 'COMPLETED'
  }
];

export const EMERGENCY_HISTORY_RECORDS = INITIAL_HISTORY_CASES;

// 6. Demo Preset Scenarios (All in Sai Baba Colony & Coimbatore)
export const DEMO_PRESET_SCENARIOS = [
  {
    category: 'ROAD_ACCIDENT',
    callerPhone: '+91 94440 11223',
    callerName: 'Senthil Nathan',
    patientName: 'Ramesh Kumar (34M)',
    condition: 'Two-wheeler collision with severe limb bleed',
    address: 'NSR Road, Sai Baba Colony, Coimbatore',
    landmark: 'Near Avila Convent, Sai Baba Colony',
    latitude: 11.0275,
    longitude: 76.9430
  },
  {
    category: 'CARDIAC_EMERGENCY',
    callerPhone: '+91 98401 22998',
    callerName: 'Kavitha Sundaram',
    patientName: 'Sundaram (62M)',
    condition: 'Severe chest crushing pain radiating to left arm',
    address: '11th Cross Road, Sai Baba Colony, Coimbatore',
    landmark: 'Behind Corporation Park, Sai Baba Colony',
    latitude: 11.0290,
    longitude: 76.9450
  },
  {
    category: 'TRAUMA',
    callerPhone: '+91 97900 44556',
    callerName: 'Saravanan M.',
    patientName: 'Mani (45M)',
    condition: 'Industrial fall with head trauma and unconsciousness',
    address: 'Mettupalayam Road, Sai Baba Colony, Coimbatore',
    landmark: 'Near Ganga Hospital Signal',
    latitude: 11.0310,
    longitude: 76.9480
  },
  {
    category: 'STROKE_NEURO',
    callerPhone: '+91 98418 77665',
    callerName: 'Anitha Raj',
    patientName: 'Lakshmi (58F)',
    condition: 'Sudden facial droop and right arm paralysis',
    address: 'Alagesan Road, Sai Baba Colony, Coimbatore',
    landmark: 'Near Bharathi Park, Sai Baba Colony',
    latitude: 11.0250,
    longitude: 76.9410
  }
];

export const IOT_DEVICES_ROSTER = [];
export const SYSTEM_SERVICES_REGISTRY = [];
